import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-7xl">
          Welcome to{" "}
          <a className="text-blue-600" href="https://nextjs.org">
            Next.js!
          </a>
        </h1>

        <p className="m-14 text-2xl">
          Get started by editing{" "}
          <code className="bg-zinc-900 py-2 px-3 rounded">pages/index.tsx</code>
        </p>

        <div className="grid grid-cols-2">
          <a
            className="rounded-lg border border-zinc-800 p-4 text-xl w-72 h-48 m-4"
            href="https://nextjs.org/docs"
          >
            <h2 className="mb-4 text-2xl">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className="rounded-lg border border-zinc-800 p-4 text-xl w-72 h-48 m-4"
            href="https://nextjs.org/learn"
          >
            <h2 className="mb-4 text-2xl">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            className="rounded-lg border border-zinc-800 p-4 text-xl w-72 h-48 m-4"
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2 className="mb-4 text-2xl">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className="rounded-lg border border-zinc-800 p-4 text-xl w-72 h-48 m-4"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="mb-4 text-2xl">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="w-full h-36 flex justify-center border-t border-zinc-800">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center h-16"
        >
          <p>Powered by</p>
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
